apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Reusable Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow-1:
    uses: CP-QA-Org/Build-Repo/.cloudbees/workflows/build-workflow.yaml
    secrets:
      GH_SECURITY_PAT: ${{ secrets.GH_SECURITY_PAT }}
  call_bar_workflow-2:
    uses: CP-QA-Org/Build-Repo/.cloudbees/workflows/second-build-workflow.yaml
    secrets:
      GH_SECURITY_PAT: ${{ secrets.GH_SECURITY_PAT }}